name: Update and Test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  update-versions-and-test:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Configure Git for private module access
        run: |
          git config --global url."https://x-access-token:${{ secrets.RO_DAVIDJSPOONER }}@github.com/davidjspooner/".insteadOf "https://github.com/davidjspooner/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}".insteadOf "https://github.com/${GITHUB_REPOSITORY}"
          echo "GOPRIVATE=github.com/davidjspooner" >> $GITHUB_ENV
          set | grep GIT

      - name: Update Go modules
        run: |
          echo "Updating Go modules"
          go get -u ./...
          go mod tidy
      - name: Run tests
        run: |
          echo "Running tests"
          go test ./... -v

      - name: Run Go vet
        run: |
          echo "Running Go vet"
          go vet ./...

      - name: Commit any changes
        run: |
          echo "Committing any changes"
          git config --global user.name "GitHub Actions"
          git config --global user.email ""
          git add .
          git status
          git commit -m "fix: Update Go modules and tidy" || echo "No changes to commit"
          git push || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-tag:
    runs-on: ubuntu-latest
    needs: update-versions-and-test
    if: github.actor != 'github-actions[bot]' && github.ref == 'refs/heads/main'
    permissions:
          contents: write  # Required for git push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch all history for so that git rev-list can find the last tag
          # This is needed for the git-update-tag command to work correctly
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Configure Git for private module access
        run: |
      - name: Configure Git for private module access
        run: |
          git config --global url."https://x-access-token:${{ secrets.RO_DAVIDJSPOONER }}@github.com/davidjspooner/".insteadOf "https://github.com/davidjspooner/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}".insteadOf "https://github.com/${GITHUB_REPOSITORY}"
          echo "GOPRIVATE=github.com/davidjspooner" >> $GITHUB_ENV
          
      - name: Increment tag if needed (main branch only)
        run: |
          echo "Incrementing tag if needed"
          go run ./cmd/ci-utility git update-tag --prefix=v --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
